# This is a basic workflow to help you get started with Actions

name: Tag test

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = 'latest';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const ref = 'tags/' + tag;
            const sha = context.sha;

            try {
              console.log(`Creating a new tag: "${tag}"`);

              const response = await github.rest.git.createRef({
                owner,
                repo,
                ref: 'refs/' + ref,
                sha,
              });
            } catch(e) {
              if (e.message === 'Reference already exists') {
                console.log('The tag already exists, updating it...');

                const response = await github.rest.git.updateRef({
                  owner,
                  repo,
                  ref,
                  sha,
                  force: true,
                });
              } else {
                throw e;
              }
            }

            console.log(`Tagged "${sha}" as the new "${tag}".`);
